spring:
  application:
    name: api-gateway

server:
  port: 8080

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  routes:
    inventory-service:
      path: /inventory/**
      url: http://inventory-service:8081
